### ISSUE TITLE
needs cocoapods support

### ISSUE THREAD

**Issue by gurhub** [SpriteKitAlliance/SKATiledMap#2]
If you could add cocoapods support it could be nice :+1:

**Comment by ghost** [comment]
It should have cocoapods support can you verify it doesn't work? [SKATiledMap](https://cocoapods.org/?q=skatiledmap)

**Comment by gurhub** [comment]
@Urthstripe29, when I check 4 days ago must be a problem in cocoapods web site, now it works, and shows : 

You want to add pod 'SKATiledMap', '~> 0.2' similar to the following to your Podfile:

target 'MyApp' do
  pod 'SKATiledMap', '~> 0.2'
end
Then run a pod install inside your terminal, or from CocoaPods.app.

Alternatively to give it a test run, run the command:

pod try SKATiledMap

thank you
